### ISSUE TITLE
[🐛 Bug]: bin/wdio clashes between packages wdio and @wdio/cli

### ISSUE THREAD

**Issue by Badisi** [webdriverio/create-wdio#16]
As stated in the [getting started guide](https://webdriver.io/docs/gettingstarted):

> To add a full WebdriverIO setup to an existing or new project, run:
> $ npx wdio .

### Issue

Actually this command can only be run once and not on an existing project (with wdio already installed), otherwise it crashes.

Ex: running `npx wdio .` twice results in the following error:

> ERROR @wdio/config:ConfigParser: Failed loading configuration file: : Cannot find module 

### Explanation

On an empty project:   
when `npx wdio .` is executed -> `npm` will download `wdio` package globally and run it.

On an existing project _(with wdio already installed)_: 
when `npx wdio .` is executed -> `npm` will use the local `wdio` available in `node_modules/.bin` but this one comes from the `@wdio/cli` package.

**Comment by christian-bromann** [comment]
@Badisi thanks for raising this issue. Not making these two (`@wdio/cli` and `wdio`) compliant to each other was a mistake on my part. I like the notion of initiating a project by calling the command followed with a path where that project is located. I am not sure if that makes sense for the `@wdio/cli` interface. Historically people started a testrun by calling `$ wdio ./wdio.conf.js`. I think we can be more smart about detecting whether a directory or a file is being passed in and whether or not it is an existing config or not.

What are your thoughts?

**Comment by Badisi** [comment]
**What about this:** 

Renaming `wdio` package to `create-wdio` and make use of [npm init](https://docs.npmjs.com/cli/v7/commands/npm-init) and [yarn create](https://classic.yarnpkg.com/en/docs/cli/create/) ?

---

That way the installation would be:

#### npm
```sh
npm init wdio .
```
#### yarn
```sh
yarn create wdio .
```
#### npx
```sh
npx create-wdio .
```

**Comment by Badisi** [comment]
But having `wdio` + `@wdio/cli config` still bugs me.

The former is doing a few extra things than the latter and then calls the latter - but yet they should serve the same goal.
This is a bit confusing to me.

Either `wdio` should be only calling `@wdio/cli config` (no extra stuff) or `wdio` should became the `@wdio/cli config`.

**Comment by christian-bromann** [comment]
> Renaming `wdio` package to `create-wdio` and make use of [npm init](https://docs.npmjs.com/cli/v7/commands/npm-init) and [yarn create](https://classic.yarnpkg.com/en/docs/cli/create/) ?

Yes, I like the idea. Not sure why we didn't went with this from the begin with. Let's do that!

**Comment by christian-bromann** [comment]
Renamed project to `create-wdio`. I will deprecate the old package.
