### ISSUE TITLE
Unable to open Allure report. Getting ERR_EMPTY_RESPONSE error.

### ISSUE THREAD

**Issue by antoniidaraiev** [webdriverio/create-wdio#212]
Report generates fine on webdriverio. But when I run `allure open`
 command, Getting ERR_EMPTY_RESPONSE error in all browsers like Chrome, Safari, Firefox. Tried different jdks, still cannot access allure report. Other people with same repo can access it, but I don't. Does anyone know how to fix that?

<img width="522" alt="Screen Shot 2022-08-03 at 2 54 25 PM" src="https://user-images.githubusercontent.com/82844082/182719375-d13acfa4-4df9-46b6-80ff-74d7e995cd69.png">

**Comment by christian-bromann** [comment]
@antoniidaraiev you have to be more descriptive about your setup. What you posted could mean anything. Where do you run your tests? How do you generate your Allure reports? Do you have a reproducible example?

**Comment by antoniidaraiev** [comment]
Found the solution. For some reason localhost didn't want to load using that IP. Had to use `http://localhost/:54107/index.html  where 54107 port from allure, should work too`. Or should specify URL in allure like `allure serve allure-results -h 127.0.0.1`

**Comment by christian-bromann** [comment]
Alright, closing then.
