### ISSUE TITLE
can not generate package.json in the target folder, always added in /Users/administrator folder 

### ISSUE THREAD

**Issue by 7999** [webdriverio/create-wdio#350]
when after run npx create-wdio@latest ./e2e in target folder with terminal, there has not package.json generated in target folder, instead of always generate the package.json file in /Users/administrator folder, although input the target folder path

**Comment by christian-bromann** [comment]
Can you please provide more information? From which directory do you call this command and how does the folder structure look like after the setup is done?

**Comment by 7999** [comment]
I work on Mac OS 12.6.2, node -v 16.15.0, npm  8.5.5
I run this command in the folder ./Users/administartor/Documents/WebdriverioTest, after executed the command, only three items generated in the folder of ./Users/administartor/Documents/WebdriverioTest, there created one folder named test, and two file named tsconfig.json, wdio.conf.ts, nothing else

**Comment by christian-bromann** [comment]
Can you provide which answers you picked for the questions?

**Comment by christian-bromann** [comment]
Can you provide which answers you picked for the questions?

**Comment by christian-bromann** [comment]
Can you provide which answers you picked for the questions?

**Comment by christian-bromann** [comment]
Can you provide which answers you picked for the questions?

**Comment by 7999** [comment]
>

> Can you provide which answers you picked for the questions?

how to make the package.json generated in the same folder with the project instead of automatically added in the folder of /Users/administrators  although i input the exact path

**Comment by christian-bromann** [comment]
@7999 well this doesn't really answer my question, it would be useful to be able to reproduce your case to understand what is going on. Note that WebdriverIO creates in some cases an addition `package.json` to allow running tests in an ESM context.

**Comment by sdoigmm** [comment]
`package-lock.json` & `package.json` are created in `/Users/Steven/` for me too.

If I run `npx create-wdio@latest ./test` in `/Users/Steven/Documents/Projects/` the first question is:

`A project was detected at "/Users/Steven", correct?`, I choose no
`What is the project root of your test project?`, I enter `/Users/Steven/Documents/Projects/test`, 

and select the following options:

- `local`
- `On my local machine`
- `Mocha`
- `No`
- `y`
- `Enter`
- `y`
- `Enter`
- `spec`
- `Enter`
- `chromedriver`
- `https://example.com`
- `y`

The `package-lock.json` & `package.json` are created in `/Users/Steven/`.

**Comment by christian-bromann** [comment]
This is the expected behavior. If you have a `package.json` in one of the parent directories, it uses that to install the dependencies to. Your tests are created in `/Users/Steven/Documents/Projects/test`. We could extend the [configuration wizard](https://github.com/webdriverio/webdriverio/blob/2a108e390cf46e37aede62ef7f9d593a59a4c174/packages/wdio-cli/src/utils.ts#L530-L544) to ask the question whether an additional `package.json` should be created or if the one found should be re-used. Any contributions for that would be welcome!

**Comment by erwinheitzman** [comment]
I believe this should be resolved when we release https://github.com/webdriverio/create-wdio/pull/585

**Comment by christian-bromann** [comment]
https://github.com/webdriverio/create-wdio/pull/585 was released.

@7999 @sdoigmm please verify and let us know if you still experience any issues. Happy to reopen. Thanks for reporting!
