### ISSUE TITLE
[HELP] Can this create same thing in ts-script instead of javascript

### ISSUE THREAD

**Issue by Redinbox** [webdriverio/create-wdio#465]
Hello,
Thanks for you valuable time and making easy setup for wido.

Currently this single setup doing great job for creating JS script project.

Is it possible same thing to support in car of TS script?

**Comment by christian-bromann** [comment]
Thanks for raising the issue.

> Is it possible same thing to support in car of TS script?

Yes, by selecting TypeScript as compiler WebdriverIO will create TypeScript files, see:

![Screenshot 2023-07-06 at 22 58 57](https://github.com/webdriverio/create-wdio/assets/731337/7980e1e1-5875-4665-807a-730208a15942)
