### ISSUE TITLE
[🐛 Bug]: Fix configuration wizard workflow when using `pnpm`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/create-wdio#548]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
n/a
```

### What happened?

When calling `pnpm create wdio` an error is thrown.

### What is your expected behavior?

The workflow should work as smooth as with npm and yarn.

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
pnpm create wdio@latest .
.../../../.pnpm-store/v3/tmp/dlx-14824   |  +50 +++++
.../../../.pnpm-store/v3/tmp/dlx-14824   | Progress: resolved 50, reused 48, downloaded 2, added 50, done

                      **** WDIO LOGO REMVOED *****

                           Webdriver.IO
              Next-gen browser and mobile automation
                    test framework for Node.js


Installing @wdio/cli to initialize project...


⚠️  Ups, something went wrong: Error calling: npm install --save-dev --loglevel error @wdio/cli@latest!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by userquin** [comment]
Windows machine, nvm, and corepack enable via pnpm:
```shell
C:\Users\Joaquín>npm version
{
  npm: '9.5.1',
  node: '18.16.0',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.0',
  brotli: '1.0.9',
  cldr: '42.0',
  icu: '72.1',
  llhttp: '6.0.10',
  modules: '108',
  napi: '8',
  nghttp2: '1.52.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.8+quic',
  simdutf: '3.2.2',
  tz: '2022g',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13'
}

C:\Users\Joaquín>pnpm --version
8.9.0
```
