### ISSUE TITLE
When i use npm init wdio@latest . error coming

### ISSUE THREAD

**Issue by dileep363** [webdriverio/create-wdio#712]
Error is like that

Installing @wdio/cli to initialize project...
✔ Success!

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? A project named "Testing" was detected at "C:\Users\Dileep.P\OneDrive\Desktop\Testing", correct? Yes
? What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
? Where is your automation backend located? On my local machine
? Which environment you would like to automate? Web - web applications in the browser
? With which browser should we start? Chrome
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use a compiler? No!
? Do you want WebdriverIO to autogenerate some test files? Yes
? What should be the location of your spec files? C:\Users\Dileep.P\OneDrive\Desktop\Testing\test\specs\**\*.js
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? C:\Users\Dileep.P\OneDrive\Desktop\Testing\test\pageobjects\**\*.js
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup?
? Would you like to include Visual Testing to your setup? For more information see
https://webdriver.io/docs/visual-testing! Yes
? Do you want to add a service to your test setup? visual
? Do you want me to run `npm install` Yes

Installing packages using npm:
- @wdio/local-runner@latest
- @wdio/mocha-framework@latest
- @wdio/spec-reporter@latest
- @wdio/visual-service
- @wdio/visual-service

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm error code 1
npm error path C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
npm error Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Dileep.P\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm error node-pre-gyp info it worked if it ends with ok
npm error node-pre-gyp info using node-pre-gyp@1.0.11
npm error node-pre-gyp info using node@22.2.0 | win32 | x64
npm error (node:36932) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
npm error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
npm error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.2.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp)
npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.2.0 | win32 | x64
npm error gyp info ok
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.2.0 | win32 | x64
npm error gyp info find Python using Python version 3.10.5 found at "C:\Users\Dileep.P\AppData\Local\Programs\Python\Python310\python.exe"
npm error gyp ERR! find VS
npm error gyp ERR! find VS msvs_version not set from command line or npm config
npm error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
npm error gyp ERR! find VS
npm error gyp ERR! find VS Failure details: undefined
npm error gyp ERR! find VS checking VS2022 (17.10.34928.147) found at:
npm error gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm error gyp ERR! find VS - found "Visual Studio C++ core features"
npm error gyp ERR! find VS - missing any VC++ toolset
npm error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm error gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
npm error gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
npm error gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
npm error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm error gyp ERR! find VS
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS You need to install the latest version of Visual Studio
npm error gyp ERR! find VS including the "Desktop development with C++" workload.
npm error gyp ERR! find VS For more information consult the documentation at:
npm error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm error gyp ERR! stack at VisualStudioFinder.fail (C:\Users\Dileep.P\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:116:11)
npm error gyp ERR! stack at VisualStudioFinder.findVisualStudio (C:\Users\Dileep.P\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:72:17)
npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm error gyp ERR! stack at async createBuildDir (C:\Users\Dileep.P\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:95:26)
npm error gyp ERR! stack at async run (C:\Users\Dileep.P\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
npm error gyp ERR! System Windows_NT 10.0.26120
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dileep.P\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=C:\\Users\\Dileep.P\\OneDrive\\Desktop\\Testing\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Dileep.P\\OneDrive\\Desktop\\Testing\\node_modules\\canvas\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
npm error gyp ERR! cwd C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas
npm error gyp ERR! node -v v22.2.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error node-pre-gyp ERR! build error
npm error node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Dileep.P\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm error node-pre-gyp ERR! System Windows_NT 10.0.26120
npm error node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dileep.P\\OneDrive\\Desktop\\Testing\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm error node-pre-gyp ERR! cwd C:\Users\Dileep.P\OneDrive\Desktop\Testing\node_modules\canvas
npm error node-pre-gyp ERR! node -v v22.2.0
npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm error node-pre-gyp ERR! not ok
npm error A complete log of this run can be found in: C:\Users\Dileep.P\AppData\Local\npm-cache\_logs\2024-06-07T09_29_10_916Z-debug-0.log
wdio.js config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have fa
                         iled                                           [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -s, --updateSnapshots  update DOM, image or test snapshots            [string]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to r
                         un the specs                                   [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined sui
                         te                                              [array]
      --spec             run only a certain spec file - overrides specs piped fr
                         om stdin                                        [array]
      --exclude          exclude certain spec file from the test run - overrides
                          exclude piped from stdin                       [array]
      --multi-run        Repeat specific specs and/or suites N times    [number]
      --mochaOpts        Mocha options
      --jasmineOpts      Jasmine options
      --cucumberOpts     Cucumber options
      --autoCompileOpts  Auto compilation options
      --coverage         Enable coverage for browser runner
      --shard            Shard tests and execute only the selected shard. Specif
                         y in the one-based form like `--shard x/y`, where x is
                         the current and y the total shard.
      --yarn             Install packages via Yarn package manager.
                                                      [boolean] [default: false]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
  -t, --npmTag           define NPM tag to use for WebdriverIO related packages
                                                    [string] [default: "latest"]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v8.38.2)

Error: Command failed with exit code 1: npm install @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest @wdio/visual-service @wdio/visual-service --save-dev
    at makeError (file:///C:/Users/Dileep.P/OneDrive/Desktop/Testing/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///C:/Users/Dileep.P/OneDrive/Desktop/Testing/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installPackages (file:///C:/Users/Dileep.P/OneDrive/Desktop/Testing/node_modules/@wdio/cli/build/install.js:24:42)
    at async npmInstall (file:///C:/Users/Dileep.P/OneDrive/Desktop/Testing/node_modules/@wdio/cli/build/utils.js:684:25)
    at async runConfigCommand (file:///C:/Users/Dileep.P/OneDrive/Desktop/Testing/node_modules/@wdio/cli/build/commands/config.js:124:5)
    at async Object.handler (file:///C:/Users/Dileep.P/OneDrive/Desktop/Testing/node_modules/@wdio/cli/build/commands/config.js:139:5) {
  shortMessage: 'Command failed with exit code 1: npm install @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest @wdio/visual-service @wdio/visual-service --save-dev',
  command: 'npm install @wdio/local-runner@latest @wdio/mocha-framework@latest @wdio/spec-reporter@latest @wdio/visual-service @wdio/visual-service --save-dev',
  escapedCommand: 'npm install "@wdio/local-runner@latest" "@wdio/mocha-framework@latest" "@wdio/spec-reporter@latest" "@wdio/visual-service" "@wdio/visual-service" --save-dev',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: 'C:\\Users\\Dileep.P\\OneDrive\\Desktop\\Testing',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

⚠️  Ups, something went wrong: Error calling: npx wdio config --npm-tag latest!
npm error code 1
npm error path C:\Users\Dileep.P\OneDrive\Desktop\Testing
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c create-wdio .
npm error A complete log of this run can be found in: C:\Users\Dileep.P\AppData\Local\npm-cache\_logs\2024-06-07T09_27_30_169Z-debug-0.log

**Comment by christian-bromann** [comment]
Can you run `npx envinfo` to provide more information?

**Comment by dileep363** [comment]
When I Run the npx envinfo the output is 

 System:
    OS: Windows 11 10.0.26120
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 8.94 GB / 15.84 GB
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 24.0 - ~\AppData\Local\Programs\Python\Python310\Scripts\pip3.EXE
  Utilities:
    Git: 2.37.0.
    Curl: 8.7.1 - C:\Windows\system32\curl.EXE
  SDKs:
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    VSCode: 1.90.0 - C:\Users\Dileep.P\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Java: 17.0.4.1
    Python: 3.10.5
  Browsers:
    Edge: Chromium (126.0.2592.13)
    Internet Explorer: 11.0.26100.1

**Comment by christian-bromann** [comment]
Thanks, our Visual service currently requires node-gyp to setup on Windows, we are about release a new version that simplifies that setup and will fix your error, please follow https://github.com/webdriverio/visual-testing/pull/362 and try again once this is merged and released.

**Comment by dileep363** [comment]
Now can I run the command npx wdio filename
Now it is working
