### ISSUE TITLE
Runs incorrect package manager

### ISSUE THREAD

**Issue by alcpereira** [webdriverio/create-wdio#769]
## Description

I was trying to reproduce a bug in wdio and I used `pnpm create wdio ./e2e`m and I was prompted with:
```sh
? Do you want me to run `npm install` yes
```

My guts tell me the issue is within `@wdio/cli`, let me know if I should open the issue in the other repo.

**Comment by christian-bromann** [comment]
This comes from [here](https://github.com/webdriverio/webdriverio/blob/3ac726b85dfd4517870d306f7b8c341caa4e3602/packages/wdio-cli/src/constants.ts#L660) and should be fixed within [`detectPackageManager`](https://github.com/webdriverio/webdriverio/blob/3ac726b85dfd4517870d306f7b8c341caa4e3602/packages/wdio-cli/src/utils.ts#L829-L838). You want to give us a hand?
